[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26"
erupt = "0.21.0+202"
color-eyre = "0.5"
flexi_logger = "0.22"
log = "0.4"